import Foundation
import Testing
@testable import AgentBar

/// The Swift reader against the dashboard's own parser. `Fixtures/permission-screens.json` holds pane
/// screens with what `classify_pane.parse_permission_block` returned for their last 100 lines
/// (generated by running the real parser); the reader must return exactly that, or nothing where it
/// returned nothing. A drift here would show up as the dashboard refusing decisions.
struct PanePermissionReaderTests {
    private struct Screen: Decodable {
        let name: String
        let lines: [String]
        let expected: DashboardPermission?
    }

    private func screens() throws -> [Screen] {
        let url = try #require(Bundle.module.url(forResource: "permission-screens", withExtension: "json", subdirectory: "Fixtures"))
        return try JSONDecoder().decode([Screen].self, from: Data(contentsOf: url))
    }

    private func screen(_ name: String) throws -> Screen {
        try #require(try screens().first { $0.name == name })
    }

    @Test func everyRecordedScreenReadsExactlyAsTheDashboardReadsIt() throws {
        let all = try screens()
        #expect(all.count >= 50)
        for screen in all {
            let read = PanePermissionReader.prompt(in: screen.lines)
            #expect(read == screen.expected?.prompt, "\(screen.name)")
        }
    }

    @Test func aLongCommandIsReadWholeFromAnUnwrappedScreen() throws {
        let read = try #require(PanePermissionReader.prompt(in: try screen("long command on one line (unwrapped read)").lines))
        #expect(read.tool == "Bash")
        #expect(read.detail == PermissionFixtures.longCommand)
        #expect(read.options.map(\.index) == [1, 2, 3])
        #expect(read.cursorIndex == 1)
    }

    /// The status feed reads the WRAPPED screen: a long command breaks over rows, no row is a
    /// `⏺ Tool(...)` receipt, and the dashboard's parser (so this one) finds no box. That is why the
    /// feed shows such a row as a plain "blocked", and why the card reads the pane afresh.
    @Test func aWrappedLongCommandIsNotAReceiptAndReadsAsNoBox() throws {
        let wrapped = try screen("long command wrapped over rows (visible read)")
        #expect(wrapped.expected == nil)
        #expect(PanePermissionReader.prompt(in: wrapped.lines) == nil)
    }

    @Test func onlyTheLastHundredLinesAreRead() throws {
        #expect(PanePermissionReader.prompt(in: try screen("box scrolled out of the last 100 lines").lines) == nil)
        #expect(PanePermissionReader.prompt(in: try screen("box inside the last 100 lines with lots of history above").lines) != nil)
    }

    @Test func aBoxBuiltFromAFixturePromptReadsBackAsThatPrompt() {
        #expect(PanePermissionReader.prompt(in: PermissionFixtures.screen(for: PermissionFixtures.bash)) == PermissionFixtures.bash)
        #expect(PanePermissionReader.prompt(in: PermissionFixtures.screen(for: PermissionFixtures.oneOff)) == PermissionFixtures.oneOff)
    }

    // MARK: - File-edit boxes

    @Test func theRealEditBoxCaptureReadsAsFileAndDiffExcerptWithTheDashboardsOwnWords() throws {
        let read = try #require(PanePermissionReader.prompt(in: try screen("REAL capture: edit box on pane p3K (Update)").lines))
        #expect(read.tool == "Update")
        #expect(read.detail == ".claude/chief-mode\n 1  on 2026-09-15T04:21:16+00:00 84ac01f3-82fa-4505-ab39-f7b06a2e15e3\n 2 +")
        #expect(read.title == "Do you want to make this edit to chief-mode?")
        #expect(read.options.map(\.label) == ["Yes", "Yes, and allow Claude to edit files in this project's .claude folder for this session", "No"])
        #expect(read.cursorIndex == 1)
        #expect(read.isFileEdit)
        #expect(read.detailParts.headline == ".claude/chief-mode")
        #expect(read.choices == [.allow, .allowAlways, .deny])
        #expect(read.option(for: .allowAlways)?.index == 2)
        #expect(read.option(for: .deny)?.index == 3)
    }

    @Test func aLongDiffIsCappedAtTwentyLinesAndSaysHowManyWereLeftOut() throws {
        let read = try #require(PanePermissionReader.prompt(in: try screen("edit box, diff of 21 lines (truncated)").lines))
        #expect(read.detail.split(separator: "\n", omittingEmptySubsequences: false).count == 1 + 20 + 1)
        #expect(read.detail.hasSuffix("… (1 more line(s) truncated)"))
        let exact = try #require(PanePermissionReader.prompt(in: try screen("edit box, diff of exactly 20 lines").lines))
        #expect(!exact.detail.contains("truncated"))
    }

    @Test func aDiffLineThatLooksLikeABorderOrAWallDoesNotEmptyTheDiffOrDropTheBox() throws {
        let border = try #require(PanePermissionReader.prompt(in: try screen("edit box, diff line that looks like a border").lines))
        #expect(border.detail.contains("BORDER2"))
        let wall = try #require(PanePermissionReader.prompt(in: try screen("edit box, diff line that looks like a wall").lines))
        #expect(wall.detail.contains("Review your answers"))
    }

    @Test func aCreateFileTitleIsNotReadBecauseTheDashboardDoesNotReadIt() throws {
        #expect(PanePermissionReader.prompt(in: try screen("create-file title is not recognised").lines) == nil)
    }

    @Test func theReceiptLookbackIsSixtyLines() throws {
        #expect(PanePermissionReader.prompt(in: try screen("edit box, receipt exactly 60 lines above the title").lines) != nil)
        #expect(PanePermissionReader.prompt(in: try screen("edit box, receipt 61 lines above the title").lines) == nil)
    }

    /// Proof, at herdr's 76 columns, that a tool box's option rows can wrap too: the real edit box's second
    /// row is 90 characters. Neither this reader nor the dashboard's joins option rows, so both read the same
    /// truncated label (a send still matches) but "for this session" falls onto the unread row and Allow always
    /// is not offered. Fixing that here alone would make the echoed label differ from the dashboard's and be
    /// refused: change both parsers together (AGENTS.md gotcha 13).
    @Test func anOptionRowWrappedAtPaneWidthLosesItsTailOnBothSidesSoAllowAlwaysIsNotOffered() throws {
        let wrapped = [
            "⏺ Update(.claude/chief-mode)", "", String(repeating: "─", count: 72),
            "   Do you want to make this edit to chief-mode?",
            "   ❯ 1. Yes",
            "     2. Yes, and allow Claude to edit files in this project's .claude folder",
            "        for this session",
            "     3. No",
        ]
        let read = try #require(PanePermissionReader.prompt(in: wrapped))
        #expect(read.options.map(\.label) == ["Yes", "Yes, and allow Claude to edit files in this project's .claude folder", "No"])
        #expect(read.choices == [.allow, .deny])
    }
}
