"""Phase 1a (docs/plans/2026-09-26-agentbar-mobile-web.md): lets the phone
reach the dashboard through `tailscale serve` (an HTTPS proxy at
https://<machine>.<tailnet>.ts.net that forwards to
127.0.0.1:<remote.port>) without loosening anything for the existing
loopback path.

QA pass 2 REDESIGN (2026-09-26): pass 1 gated remote requests by inspecting
the Host header on the SAME listener (127.0.0.1:4711) everything else uses,
and treated a Tailscale identity header as proof the request was proxied in.
That header is Tailscale's own defense against Host spoofing, but
`tailscale serve` only adds it for a *tagged* device's requests — a
personal/untagged phone can reach the proxy with none of those headers set,
which would have made every request from it indistinguishable from a
genuine loopback call again. Host-header trust is gone entirely now:

  - The main listener (127.0.0.1:4711) runs NO remote-access code at all —
    see chief-dashboard-server.py's Handler, which now only calls into this
    module when `self.server.remote_listener` is True.
  - A SEPARATE listener (127.0.0.1:<remote.port>, default 4712) is bound
    only when `remote.enabled` is true in config.json. `tailscale serve`
    targets THIS port, never 4711 — nothing on the tailnet can reach 4711 at
    all, so there is no Host header to spoof against it in the first place.
    Every request that arrives on the remote listener is, by construction,
    remote: auth is required on every route, unconditionally, regardless of
    whatever Host or identity headers it happens to carry.

Design choices (kept here, not spread across the server):
  - Token: one shared secret in a mode-600 file
    (~/.config/agent-dashboard/remote-token), generated by
    `scripts/remote-token.py`. Compared with hmac.compare_digest (constant
    time) so response timing can't leak how many characters matched.
  - Session: the login form exchanges the token for a session id
    (secrets.token_urlsafe(32) — 256 bits, unguessable on its own) held in
    a server-side map {sha256(session_id): (expires_at, token_fp)}. The map
    is also saved to SESSIONS_PATH (mode 0600, next to the token) so a
    dashboard restart — ~10x a day — does not log the phone out (it used to:
    the map was memory-only, and every restart meant re-pasting the token).
    Only HASHES of session ids are written, so the file is not a cookie
    jar; a file that is not a private (0600) regular file is ignored, like
    the token. Rotation still revokes: every entry carries the fingerprint
    of the token it was issued under. Not HMAC-derived either: a plain
    server-side map avoids a second secret (a cookie-signing key) to
    generate, store and rotate. Cookie is HttpOnly + Secure +
    SameSite=Strict so it never reaches page JS and is never sent
    cross-site or over plain HTTP. Sessions are no longer bound to a
    specific `remote.hosts` entry (pass 1's `host` field) — the remote
    listener doesn't trust Host either, so there is nothing meaningful left
    to bind against; a session is simply "logged in on the remote
    listener," full stop.
  - CSRF: a write's `Origin` header, when the browser sends one, must name
    one of `remote.hosts` over https — never anything else. This is the
    ONLY remaining use of `remote.hosts`: an allow-list for Origin
    comparison, not a Host-header identity check.
  - Rate limiting: a small in-memory backoff per client IP (not per token
    guess) — this is a single-user personal server, the goal is only to
    slow down a brute-force script, not to defend a multi-tenant login.
  - Audit log: JSONL, one line per remote write attempt (allowed or
    refused), in the same config dir as the token so both live under one
    "remote access" folder an operator can find together.
"""
import hashlib
import hmac
import json
import os
import secrets
import stat
import threading
import time
from urllib.parse import urlsplit

import dashboard_config

TOKEN_PATH = os.path.join(dashboard_config.CONFIG_HOME, "remote-token")
AUDIT_LOG_PATH = os.path.join(dashboard_config.CONFIG_HOME, "remote-audit.jsonl")
#: Issued phone sessions, so a dashboard restart keeps them (hashed ids only).
SESSIONS_PATH = os.path.join(dashboard_config.CONFIG_HOME, "remote-sessions.json")

#: `tailscale serve` fronts this port when remote access is enabled — the
#: main dashboard listener (4711 by default) is never reachable from the
#: tailnet at all, so there is no Host header on it to spoof. Configurable
#: via config.json's `remote.port`.
DEFAULT_REMOTE_PORT = 4712

SESSION_COOKIE_NAME = "agentbar_remote_session"
SESSION_TTL_SECONDS = 30 * 24 * 60 * 60  # 30 days — a phone stays logged in

#: Failed-login backoff: after this many failures from one IP within the
#: window, further attempts are refused (429) until the window rolls off.
LOGIN_MAX_FAILURES = 5
LOGIN_WINDOW_SECONDS = 60

_LOCK = threading.Lock()
#: {sha256(session_id): (expires_at_epoch, token_fingerprint_at_issue)},
#: loaded from SESSIONS_PATH on first use (None = not loaded yet).
_SESSIONS = None
#: {client_ip: [failure_epoch, ...]} — pruned to LOGIN_WINDOW_SECONDS on read
_LOGIN_FAILURES = {}


def load_remote_settings(path=None):
    """(enabled, hosts, port) — hosts is a set of lowercase hostnames (no
    port, no scheme) taken from config.json's `remote` block, used ONLY as
    the Origin allow-list for CSRF (see module docstring). `port` is where
    the separate remote listener binds (127.0.0.1 only), default 4712.

        {"remote": {"enabled": true, "hosts": ["mymac.tailnet.ts.net"],
                     "port": 4712}}

    Missing file / missing key / wrong type all mean "disabled" — remote
    access is opt-in, never inferred."""
    path = path or dashboard_config.CONFIG_PATH
    raw = {}
    if os.path.exists(path):
        try:
            with open(path) as f:
                raw = json.load(f) or {}
        except (OSError, json.JSONDecodeError):
            raw = {}
    remote = raw.get("remote") if isinstance(raw, dict) else None
    if not isinstance(remote, dict):
        return False, set(), DEFAULT_REMOTE_PORT
    enabled = bool(remote.get("enabled"))
    hosts_raw = remote.get("hosts") or []
    if not isinstance(hosts_raw, list):
        hosts_raw = []
    hosts = {str(h).strip().lower() for h in hosts_raw if str(h).strip()}
    try:
        port = int(remote.get("port") or DEFAULT_REMOTE_PORT)
    except (TypeError, ValueError):
        port = DEFAULT_REMOTE_PORT
    return enabled, hosts, port


def strip_port(netloc):
    """Lowercase hostname out of a `host[:port]` or bracketed-IPv6 netloc."""
    netloc = (netloc or "").strip()
    if netloc.startswith("["):
        return netloc[1:].split("]")[0].lower()
    return netloc.split(":")[0].lower()


def origin_allowed(origin_header, configured_hosts):
    """True when `origin_header` is present and names an https:// origin
    whose hostname is one of `configured_hosts`. False for anything else,
    including a missing/unparsable Origin — callers decide separately
    whether "no Origin at all" (a curl call, or a fetch that never sends
    one) should be treated as allowed; this function only answers "does the
    Origin that WAS sent check out."""
    if not origin_header or not configured_hosts:
        return False
    try:
        parsed = urlsplit(origin_header)
    except ValueError:
        return False
    if parsed.scheme != "https":
        return False
    return strip_port(parsed.netloc) in configured_hosts


def load_token():
    """The configured remote token, or None if no token file exists yet
    (remote access can be `enabled: true` before a token is generated —
    every remote request just gets refused until one is), the file is
    empty, or the file's permissions are looser than 0600 (group/other
    read or write bits set). A world/group-readable token file has already
    leaked the shared secret to any other local account on this Mac — this
    module must not keep trusting it silently once that happens; treat it
    the same as "no token configured" until an operator fixes the mode
    (scripts/remote-token.py always writes 0600)."""
    try:
        st = os.stat(TOKEN_PATH)
    except OSError:
        return None
    if stat.S_IMODE(st.st_mode) & 0o077:
        return None
    try:
        with open(TOKEN_PATH) as f:
            value = f.read().strip()
    except OSError:
        return None
    return value or None


def token_fingerprint(token):
    """A short, non-secret fingerprint of `token` (or None for "no token"),
    used to bind a session to the token that was live when it was issued —
    never the raw token itself, so the fingerprint is safe to hold in the
    in-memory session map and, if ever logged, leaks nothing usable to
    re-derive the token (sha256 is one-way; this is an equality check, not
    a place needing anything token-derivation-resistant beyond that)."""
    if not token:
        return None
    return hashlib.sha256(token.encode("utf-8")).hexdigest()


def _client_key(client_address):
    try:
        return str(client_address[0])
    except Exception:
        return "unknown"


def is_login_blocked(client_address):
    key = _client_key(client_address)
    now = time.time()
    with _LOCK:
        attempts = [t for t in _LOGIN_FAILURES.get(key, []) if now - t < LOGIN_WINDOW_SECONDS]
        _LOGIN_FAILURES[key] = attempts
        return len(attempts) >= LOGIN_MAX_FAILURES


def record_login_failure(client_address):
    key = _client_key(client_address)
    with _LOCK:
        _LOGIN_FAILURES.setdefault(key, []).append(time.time())


def clear_login_failures(client_address):
    key = _client_key(client_address)
    with _LOCK:
        _LOGIN_FAILURES.pop(key, None)


def verify_token(candidate, token=None):
    token = load_token() if token is None else token
    if not token or not candidate:
        return False
    return hmac.compare_digest(candidate, token)


def create_session():
    """New session id bound to a fingerprint of the token that was live at
    login time. Rotating the token (scripts/remote-token.py --rotate)
    changes that fingerprint, so every session issued under the old token
    stops validating on its very next request — rotation revokes, it
    doesn't just block future logins."""
    session_id = secrets.token_urlsafe(32)
    expires_at = time.time() + SESSION_TTL_SECONDS
    token_fp = token_fingerprint(load_token())
    with _LOCK:
        sessions = _loaded_sessions()
        sessions[_session_key(session_id)] = (expires_at, token_fp)
        _save_sessions(sessions)
    return session_id


def session_valid(session_id):
    """True when `session_id` is a still-valid, still-logged-in session:
    not missing, not expired, and issued under the token that is still the
    current one (a rotated/removed token invalidates every session that was
    issued under the old one)."""
    if not session_id:
        return False
    current_fp = token_fingerprint(load_token())
    key = _session_key(session_id)
    with _LOCK:
        sessions = _loaded_sessions()
        entry = sessions.get(key)
        if not entry:
            return False
        expires_at, token_fp = entry
        if time.time() >= expires_at or token_fp != current_fp:
            del sessions[key]
            _save_sessions(sessions)
            return False
        return True


def _session_key(session_id):
    """What the map (and file) holds for a session: its sha256, never the
    id itself — reading the file must not yield a usable cookie."""
    return hashlib.sha256(session_id.encode("utf-8")).hexdigest()


def _loaded_sessions():
    """The session map, read from SESSIONS_PATH on first use. Call with
    _LOCK held. Expired entries are dropped; a missing, unreadable, or
    non-private file (group/other bits, not a regular file) starts empty."""
    global _SESSIONS
    if _SESSIONS is None:
        _SESSIONS = _read_sessions_file()
    return _SESSIONS


def _read_sessions_file():
    try:
        st = os.lstat(SESSIONS_PATH)
        if not stat.S_ISREG(st.st_mode) or stat.S_IMODE(st.st_mode) & 0o077:
            return {}
        with open(SESSIONS_PATH) as f:
            raw = json.load(f)
    except (OSError, ValueError):
        return {}
    now = time.time()
    sessions = {}
    for key, entry in (raw.items() if isinstance(raw, dict) else ()):
        if isinstance(key, str) and isinstance(entry, list) and len(entry) == 2 \
                and isinstance(entry[0], (int, float)) and entry[0] > now \
                and (entry[1] is None or isinstance(entry[1], str)):
            sessions[key] = (float(entry[0]), entry[1])
    return sessions


def _save_sessions(sessions):
    """Atomic, mode-0600 write of the session map. Best-effort: a failed
    write only means a restart logs the phone out again, never a failed
    login. Call with _LOCK held."""
    tmp_path = f"{SESSIONS_PATH}.{os.getpid()}.tmp"
    try:
        os.makedirs(os.path.dirname(SESSIONS_PATH), exist_ok=True)
        fd = os.open(tmp_path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
        with os.fdopen(fd, "w") as f:
            json.dump({key: list(entry) for key, entry in sessions.items()}, f)
        os.chmod(tmp_path, 0o600)
        os.replace(tmp_path, SESSIONS_PATH)
    except OSError:
        try:
            os.remove(tmp_path)
        except OSError:
            pass


def parse_cookies(cookie_header):
    """{name: value} from a Cookie header — stdlib http.cookies is
    overkill (it round-trips through Morsel objects) for one flat lookup."""
    jar = {}
    if not cookie_header:
        return jar
    for part in cookie_header.split(";"):
        if "=" not in part:
            continue
        name, _, value = part.strip().partition("=")
        if name:
            jar[name] = value
    return jar


def session_cookie_header(session_id, secure=True):
    attrs = [
        f"{SESSION_COOKIE_NAME}={session_id}",
        "Path=/",
        "HttpOnly",
        "SameSite=Strict",
        f"Max-Age={SESSION_TTL_SECONDS}",
    ]
    if secure:
        attrs.append("Secure")
    return "; ".join(attrs)


def clear_session_cookie_header():
    return f"{SESSION_COOKIE_NAME}=; Path=/; HttpOnly; SameSite=Strict; Max-Age=0"


def append_audit(route, method, status, row_id=None, ok=None):
    """One JSONL line per remote write attempt (allowed or refused) to
    AUDIT_LOG_PATH. `ok` is the JSON reply's own `ok` (None when the reply
    has none): most write routes answer a refusal with HTTP 200
    `{ok: false}`, so `status` alone can't tell a persona start that ran
    from one that was refused. Best-effort: a write failure here must never
    break the request it's auditing, so I/O errors are swallowed."""
    entry = {
        "ts": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "route": route,
        "method": method,
        "rowId": row_id,
        "status": status,
        "ok": ok,
    }
    try:
        os.makedirs(os.path.dirname(AUDIT_LOG_PATH), exist_ok=True)
        with open(AUDIT_LOG_PATH, "a") as f:
            f.write(json.dumps(entry, default=str) + "\n")
    except OSError:
        pass


LOGIN_PAGE_HTML = """<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>AgentBar remote login</title>
<style>
  body {{ font-family: -apple-system, sans-serif; background: #111; color: #eee;
         display: flex; align-items: center; justify-content: center;
         min-height: 100vh; margin: 0; padding: 16px; box-sizing: border-box; }}
  form {{ width: 100%; max-width: 360px; }}
  h1 {{ font-size: 18px; margin: 0 0 16px; }}
  input {{ width: 100%; font-size: 16px; padding: 12px; border-radius: 8px;
           border: 1px solid #444; background: #1c1c1c; color: #eee;
           box-sizing: border-box; margin-bottom: 12px; }}
  button {{ width: 100%; font-size: 16px; padding: 12px; border-radius: 8px;
            border: none; background: #2b6cb0; color: #fff; }}
  .error {{ color: #f66; margin-bottom: 12px; }}
</style>
</head>
<body>
<form method="POST" action="/remote/login">
  <h1>AgentBar remote access</h1>
  {error_html}
  <input type="password" name="token" placeholder="Access token" autofocus autocomplete="off">
  <button type="submit">Sign in</button>
</form>
</body>
</html>
"""


def render_login_page(error=None):
    error_html = f'<div class="error">{error}</div>' if error else ""
    return LOGIN_PAGE_HTML.format(error_html=error_html).encode("utf-8")


def parse_login_form(raw_body):
    """token from either a JSON body ({"token": "..."}) or a normal HTML
    form post (application/x-www-form-urlencoded) — the login page above
    posts the form-encoded way, but a script driving this over curl/tests
    is simplest with JSON, so accept either."""
    raw_body = raw_body or b""
    text = raw_body.decode("utf-8", "replace").strip()
    if not text:
        return ""
    if text.startswith("{"):
        try:
            return str(json.loads(text).get("token") or "")
        except (json.JSONDecodeError, AttributeError):
            return ""
    from urllib.parse import parse_qs
    parsed = parse_qs(text)
    values = parsed.get("token") or []
    return values[0] if values else ""
