"""Phase 1a (docs/plans/2026-09-26-agentbar-mobile-web.md): lets the phone
reach the dashboard through `tailscale serve` (an HTTPS proxy at
https://<machine>.<tailnet>.ts.net that forwards to 127.0.0.1:<port>) without
loosening anything for the existing loopback path.

Nothing in this module changes behaviour unless `remote.enabled` is true in
config.json AND the request's Host header names one of `remote.hosts`. Every
loopback request (Host is 127.0.0.1/localhost/[::1]) never touches this
module at all — see the two call sites in chief-dashboard-server.py.

Design choices (kept here, not spread across the server):
  - Token: one shared secret in a mode-600 file
    (~/.config/agent-dashboard/remote-token), generated by
    `scripts/remote-token.py`. Compared with hmac.compare_digest (constant
    time) so response timing can't leak how many characters matched.
  - Session: the login form exchanges the token for a session id
    (secrets.token_urlsafe(32) — 256 bits, unguessable on its own) held in
    an in-memory dict {session_id: (host, expires_at)} on this process.
    Deliberately NOT persisted or HMAC-derived: the token file is already
    the durable secret, a restart only costs the phone one re-login (a tap),
    and a plain server-side map avoids a second secret (a cookie-signing
    key) to generate, store and rotate. Cookie is HttpOnly + Secure +
    SameSite=Strict so it never reaches page JS and is never sent
    cross-site or over plain HTTP.
  - Rate limiting: a small in-memory backoff per client IP (not per token
    guess) — this is a single-user personal server, the goal is only to
    slow down a brute-force script, not to defend a multi-tenant login.
  - Audit log: JSONL, one line per remote write attempt (allowed or
    refused), in the same config dir as the token so both live under one
    "remote access" folder an operator can find together.
"""
import hmac
import json
import os
import secrets
import threading
import time

import dashboard_config

TOKEN_PATH = os.path.join(dashboard_config.CONFIG_HOME, "remote-token")
AUDIT_LOG_PATH = os.path.join(dashboard_config.CONFIG_HOME, "remote-audit.jsonl")

SESSION_COOKIE_NAME = "agentbar_remote_session"
SESSION_TTL_SECONDS = 30 * 24 * 60 * 60  # 30 days — a phone stays logged in

#: Failed-login backoff: after this many failures from one IP within the
#: window, further attempts are refused (429) until the window rolls off.
LOGIN_MAX_FAILURES = 5
LOGIN_WINDOW_SECONDS = 60

_LOCK = threading.Lock()
#: {session_id: (host, expires_at_epoch)}
_SESSIONS = {}
#: {client_ip: [failure_epoch, ...]} — pruned to LOGIN_WINDOW_SECONDS on read
_LOGIN_FAILURES = {}


def load_remote_settings(path=None):
    """(enabled, hosts) — hosts is a set of lowercase hostnames (no port,
    no scheme) taken from config.json's `remote` block:

        {"remote": {"enabled": true, "hosts": ["mymac.tailnet.ts.net"]}}

    Missing file / missing key / wrong type all mean "disabled" — remote
    access is opt-in, never inferred."""
    path = path or dashboard_config.CONFIG_PATH
    raw = {}
    if os.path.exists(path):
        try:
            with open(path) as f:
                raw = json.load(f) or {}
        except (OSError, json.JSONDecodeError):
            raw = {}
    remote = raw.get("remote") if isinstance(raw, dict) else None
    if not isinstance(remote, dict):
        return False, set()
    enabled = bool(remote.get("enabled"))
    hosts_raw = remote.get("hosts") or []
    if not isinstance(hosts_raw, list):
        hosts_raw = []
    hosts = {str(h).strip().lower() for h in hosts_raw if str(h).strip()}
    return enabled, hosts


def strip_port(netloc):
    """Lowercase hostname out of a `host[:port]` or bracketed-IPv6 netloc —
    shared by Host-header and Origin-header parsing so both use the exact
    same notion of "hostname"."""
    netloc = (netloc or "").strip()
    if netloc.startswith("["):
        return netloc[1:].split("]")[0].lower()
    return netloc.split(":")[0].lower()


def matched_remote_host(host_header, configured_hosts):
    """The configured remote hostname this request's Host header names, or
    None. Port is ignored (tailscale serve fronts 443; a client testing
    against a bare port still matches by hostname)."""
    if not configured_hosts:
        return None
    host = strip_port(host_header)
    return host if host in configured_hosts else None


def load_token():
    """The configured remote token, or None if no token file exists yet
    (remote access can be `enabled: true` before a token is generated —
    every remote request just gets refused until one is)."""
    try:
        with open(TOKEN_PATH) as f:
            value = f.read().strip()
    except OSError:
        return None
    return value or None


def _client_key(client_address):
    try:
        return str(client_address[0])
    except Exception:
        return "unknown"


def is_login_blocked(client_address):
    key = _client_key(client_address)
    now = time.time()
    with _LOCK:
        attempts = [t for t in _LOGIN_FAILURES.get(key, []) if now - t < LOGIN_WINDOW_SECONDS]
        _LOGIN_FAILURES[key] = attempts
        return len(attempts) >= LOGIN_MAX_FAILURES


def record_login_failure(client_address):
    key = _client_key(client_address)
    with _LOCK:
        _LOGIN_FAILURES.setdefault(key, []).append(time.time())


def clear_login_failures(client_address):
    key = _client_key(client_address)
    with _LOCK:
        _LOGIN_FAILURES.pop(key, None)


def verify_token(candidate, token=None):
    token = load_token() if token is None else token
    if not token or not candidate:
        return False
    return hmac.compare_digest(candidate, token)


def create_session(host):
    """New session id bound to `host` (the remote hostname it was issued
    for — a cookie minted for one ts.net name is only ever honoured for
    requests carrying that same Host, see session_host below)."""
    session_id = secrets.token_urlsafe(32)
    expires_at = time.time() + SESSION_TTL_SECONDS
    with _LOCK:
        _SESSIONS[session_id] = (host, expires_at)
    return session_id


def session_host(session_id):
    """The host a still-valid session was issued for, or None (missing,
    expired, or bound to a different host than the caller expects — callers
    pass the current request's matched host and compare themselves)."""
    if not session_id:
        return None
    with _LOCK:
        entry = _SESSIONS.get(session_id)
        if not entry:
            return None
        host, expires_at = entry
        if time.time() >= expires_at:
            del _SESSIONS[session_id]
            return None
        return host


def parse_cookies(cookie_header):
    """{name: value} from a Cookie header — stdlib http.cookies is
    overkill (it round-trips through Morsel objects) for one flat lookup."""
    jar = {}
    if not cookie_header:
        return jar
    for part in cookie_header.split(";"):
        if "=" not in part:
            continue
        name, _, value = part.strip().partition("=")
        if name:
            jar[name] = value
    return jar


def session_cookie_header(session_id, secure=True):
    attrs = [
        f"{SESSION_COOKIE_NAME}={session_id}",
        "Path=/",
        "HttpOnly",
        "SameSite=Strict",
        f"Max-Age={SESSION_TTL_SECONDS}",
    ]
    if secure:
        attrs.append("Secure")
    return "; ".join(attrs)


def clear_session_cookie_header():
    return f"{SESSION_COOKIE_NAME}=; Path=/; HttpOnly; SameSite=Strict; Max-Age=0"


def append_audit(host, route, method, status, row_id=None):
    """One JSONL line per remote write attempt (allowed or refused) to
    AUDIT_LOG_PATH. Best-effort: a write failure here must never break the
    request it's auditing, so I/O errors are swallowed."""
    entry = {
        "ts": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "host": host,
        "route": route,
        "method": method,
        "rowId": row_id,
        "status": status,
    }
    try:
        os.makedirs(os.path.dirname(AUDIT_LOG_PATH), exist_ok=True)
        with open(AUDIT_LOG_PATH, "a") as f:
            f.write(json.dumps(entry, default=str) + "\n")
    except OSError:
        pass


LOGIN_PAGE_HTML = """<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>AgentBar remote login</title>
<style>
  body {{ font-family: -apple-system, sans-serif; background: #111; color: #eee;
         display: flex; align-items: center; justify-content: center;
         min-height: 100vh; margin: 0; padding: 16px; box-sizing: border-box; }}
  form {{ width: 100%; max-width: 360px; }}
  h1 {{ font-size: 18px; margin: 0 0 16px; }}
  input {{ width: 100%; font-size: 16px; padding: 12px; border-radius: 8px;
           border: 1px solid #444; background: #1c1c1c; color: #eee;
           box-sizing: border-box; margin-bottom: 12px; }}
  button {{ width: 100%; font-size: 16px; padding: 12px; border-radius: 8px;
            border: none; background: #2b6cb0; color: #fff; }}
  .error {{ color: #f66; margin-bottom: 12px; }}
</style>
</head>
<body>
<form method="POST" action="/remote/login">
  <h1>AgentBar remote access</h1>
  {error_html}
  <input type="password" name="token" placeholder="Access token" autofocus autocomplete="off">
  <button type="submit">Sign in</button>
</form>
</body>
</html>
"""


def render_login_page(error=None):
    error_html = f'<div class="error">{error}</div>' if error else ""
    return LOGIN_PAGE_HTML.format(error_html=error_html).encode("utf-8")


def parse_login_form(raw_body):
    """token from either a JSON body ({"token": "..."}) or a normal HTML
    form post (application/x-www-form-urlencoded) — the login page above
    posts the form-encoded way, but a script driving this over curl/tests
    is simplest with JSON, so accept either."""
    raw_body = raw_body or b""
    text = raw_body.decode("utf-8", "replace").strip()
    if not text:
        return ""
    if text.startswith("{"):
        try:
            return str(json.loads(text).get("token") or "")
        except (json.JSONDecodeError, AttributeError):
            return ""
    from urllib.parse import parse_qs
    parsed = parse_qs(text)
    values = parsed.get("token") or []
    return values[0] if values else ""
