name: GitHub Release

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Create release notes
        env:
          GH_TOKEN: ${{ github.token }}
          TAG_NAME: ${{ github.ref_name }}
        run: gh release create "${TAG_NAME}" --generate-notes --latest --title "${TAG_NAME}"
